<?php
    function get_cr_email_template(){
    return '<!DOCTYPE html>'
    .'    <html lang="es">'
    .'    <head>'
    .'        <meta charset="UTF-8">'
    .'        <meta name="viewport" content="width=device-width, initial-scale=1.0">'
    .'        <title>Calculadora de creditos</title>'
    .'        <style>'
    .'            .form input{'
    .'                width: 15em'
    .'            }'
    .'            .form select{'
    .'                width: 15em'
    .'            }'
    .'            .form label {'
    .'                margin-right: 1em'
    .'            }'
    .'            .tablaCalculo, th, td {'
    .'                border: solid black 0.05em;'
    .'                padding: .5em;'
    .'                border-collapse: collapse;'
    .'                border-bottom: 1em;'
    .'            }'
    .'            .title  {'
    .'                color: black;'
    .'                background-color: rgb(117, 183, 221)'
    .'            }'
    .'            .titleBig {'
    .'                color: white;'
    .'                background-color: #0078bf;'
    .'                font-weight: bold;'
    .'                font-size: larger;'
    .'            }'
    .'        </style>'
    .'    </head>'
    .'    <body>'
    .'    <h3>MODELO DE CÁLCULO DE CUPO DE CRÉDITO PERSONAL SIN FIADOR</h3>'
    .'    <form>'
    .'        <div style="overflow-y: auto; max-height: 50em" >'
    .'            <table class="tablaCalculo">'
    .'                <tr class="title">'
    .'                    <td>Ingreso Bruto en colones</label></td>'
    .'                    <td>{ingresoBruto}</td>'
    .'                </tr>'
    .'                <tr class="title">'
    .'                    <td>Total de Deudas SUGEF</td>'
    .'                    <td>{deudaSugef}</td>'
    .'                </tr>'
    .'                <tr class="titleBig">'
    .'                    <td>CUPO DE CRÉDITO NETO (cuota)</td>'
    .'                    <td>{cupoCredito}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Tipo de cambio compra</td>'
    .'                    <td>{tipoCambio}</td>'
    .'                </tr>'
    .'                <tr class="title">'
    .'                    <td>Ingreso Neto en dólares</td>'
    .'                    <td>{ingresoNeto}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Asalariado con depósito en la entidad financiera</td>'
    .'                    <td>{esAsalariado}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Rebajo automático</td>'
    .'                    <td>{rebajoAutomatico}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Nivel SUGEF (1 a 4)</td>'
    .'                    <td>{nivelSugef}</select>'
    .'                    </td>'
    .'                </tr>'
    .'                <tr >'
    .'                    <td>Promedio de atraso de pagos (en días)</td>'
    .'                    <td>{promedioCuotas}</td>'
    .'                </tr>'
    .'                <tr class="title">'
    .'                    <td>% De endeudamiento según DAC</td>'
    .'                    <td>{porcentajeDeuda}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Cupo Credito Neto Colones</td>'
    .'                    <td>{creditoColones}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Cupo Credito Neto Dolares</td>'
    .'                    <td>{creditoDolares}</td>'
    .'                </tr>'
    .'                <tr style="color: white; font-size: larger; background-color: rgb(117, 183, 221)">'
    .'                    <td style="width: 550px" colspan="2">CONDICIONES DE CRÉDITO OFRECER</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Tasa de interés</td>'
    .'                    <td>{tasa}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Plazo</td>'
    .'                    <td>{plazo}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Tasa de interés</td>'
    .'                    <td>{tasa}</td>'
    .'                </tr>'
    .'                <tr class="titleBig">'
    .'                    <td>Monto a ofrecer colones</td>'
    .'                    <td>{sugerenciaColones}</td>'
    .'                </tr>'
    .'                <tr class="titleBig">'
    .'                    <td>Monto a ofrecer dólares</td>'
    .'                    <td>{sugerenciaDolares}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>MONEDA DESEADA POR EL CLIENTE</td>'
    .'                    <td>'
    .'                        {moneda}'
    .'                    </td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Monto solicitado</td>'
    .'                    <td>{montoSolicitado}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Tasa de interés %</td>'
    .'                    <td>{tasa}</td>'
    .'                </tr>'
    .'                <tr>'
    .'                    <td>Plazo</label></td>'
    .'                    <td>{plazo}</td>'
    .'                </tr>'
    .'                <tr class="title">'
    .'                    <td>Cuota crédito solicitado</td>'
    .'                    <td>{montoCuotaFinal}</td>'
    .'                </tr>'
    .'            </table>'
    .'        </div>'
    .'    </form>'
    .'</body>'
    .'</html>';
    }
?>